name: Print Software Versions
on:
  push:
    branches: main

jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js Version
        run: node --version
      - name: Print npm Version
        run: npm --version
      - name: Print OS Details
        run: uname -a

  PrintDBMSVersions:
    runs-on: ubuntu-24.04
    needs: [PrintLanguageVersions]
    steps:
      - name: Install SQLite3
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3
          echo "SQLite3 installation complete"
      - name: Check if SQLite3 is installed
        run: |
          which sqlite3
          sqlite3 --version
      - name: Print SQLite Version
        run: sqlite3 --version
